server {
    listen [::]:80 ipv6only=off;
    server_name your_domain_or_ip; # Change to your domain or IP

    # START ASSUREWALLOS MOD
    client_max_body_size 25M;
    # END ASSUREWALLOS MOD

    root /var/www/html; # Change to your web root directory

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # START ASSUREWALLOS MOD
    location ^~ /images/uploads/insurance_docs/ {
        deny all;
        return 403;
    }
    # END ASSUREWALLOS MOD

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/var/run/php-fpm.sock; # Adjust the path if necessary
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Additional configuration if needed
}